### PR TITLE
Repository cleanup from compiled files and relative paths

### PR DESCRIPTION
**Pull request by yozik04**
It is a bad practice to check in compiled files. I'd recommend to delete them. They are totally useless in the repository. Everyone compiles their own binary files anyway.
*.sbx
*.obl
*.sm8
*.map
*.o
*.la
*.a
*.ls

Let's keep only compiled end result for now (.stp and .sx). In future we need to move it out from the repository to a special place (Releases)

### CODE REVIEW

**Comment by nielsonm236** [comment]
I've looked through this and don't see anything that worries me (although it will be interesting to see if .gitattributes does anything of consequence). I've not done a merge before - from reading I think I know what to do. Are you ready for me to proceed?
FYI, I'm going to have to do one final "file replacement" in my repository to catch up recent changes, then I can start doing code changes properly in the repository.

**Comment by yozik04** [comment]
.gitattributes config just keeps line endings intact. Otherwise it replaced all line endings to linux version on my machine.

**Comment by yozik04** [comment]
I recommend you to merge my changes before you will commit yours. Otherwise you will commit binary files and we will have a conflict.

**Comment by yozik04** [comment]
After you merge make sure you do `git pull` on your repository folder

**Comment by yozik04** [comment]
Wohoo. Congrats with first merged Pull Request 🥳

**Comment by nielsonm236** [comment]
Did the merge and pull origin into my repository. I have pending changes but it will be another 12 hours or so before I can add them. I have a long test running regarding performance enhancements, and can't test my other changes until that completes. You'll see my new adds during your night.
Mike

**Comment by nielsonm236** [comment]
My manual copy of files from my offline directory changed the .stp files back to absolute paths. I manually edited them to match what you had done. From here forward I will do code and document changes only in the GitHub repository.

**Pull request merged**
