### PR TITLE
Added REST command /50 (at /80)

### PR DESCRIPTION
**Pull request by peoyli**
REST command /50 for batch mode pin change with return of status (as /98 /99)

### CODE REVIEW

**Comment by nielsonm236** [comment]
Hi @peoyli 
Did you test the above ... and did it work? I',m asking because providing the mask & pin settings only sets up a "Pending" condition. The main loop then needs to run to process that Pending state via check_runtime_changes() where the pin settings will be driven to the outputs.
If the same command generates the Short Form GUI output I think it will display current pin states ... not the states created by the concurrent mask & pin settings.
If two separate commands are executed then the first one (mask & pin settings) will be processed, following the second one (display result).
Mike

**Comment by peoyli** [comment]
Yes, it's tested and it works, I get the result back to whatever calls the command (curl, php)

**Comment by nielsonm236** [comment]
OK - I will probably implement it a little differently. Rather than use "50" I'll use "84".

I'm getting ready to send out a pre-release of the PCF8574 and Selectable Pinout code. This will be included.

Mike

**Comment by nielsonm236** [comment]
For the moment this command only supports IO 1 to 16. It does not support the additional PCF8574 IO.

**Comment by peoyli** [comment]
I used /50 to group it with the /55 and /56 which also changes multiple outputs at the same time (so, actually I think /80 would have been /50 in the first place, but that's maybe too late to change 3 months later). Are you possibly in progress of changing /55 and /56 to /85 and /86 ?

**Comment by nielsonm236** [comment]
I understand the logic of your thinking, and it makes sense. Some information to explain my thinking:
- The command set evolved from the original factory command set into what we have now. Emulating the original command set made sense when all I was doing was fixing the problems in the factory code.
- Since then a lot of functionality has been added and I had to work around what I started with, plus the limitation of "Decimal" commands.
- As I added the PCF8574 (8 pins) it seemed to make sense to simply continue the Decimal commands using /32 to /47 to add ON/OFF commands for pins 17 to 24 (the 8 pins on the PCF8574).
- I was thinking "What if we add more pins?". I thought we should keep the space above command /47 free in case that happened. But the reality is that /55 and /56 must be kept to maintain emulation of the original factory set. I can't add more than 3 more pins beyond the PCF8574 without bumping into /55 and /56 ... so this should not be a reason to avoid use of /50 as you have proposed.
- I have learned an important lesson with the implementation of PCF8574: It is very painful to add IO pins. The driver itself is only a couple of hundred bytes, but all the impacts related to Linked pins, GUI interface, MQTT interface, Pinout Options (for pins 1 to 16), and entry error checking are more than 10 times more code. As a result test and debug were very time consuming. I don't think I will do that again! This is supposed to be a hobby ... not a job :-)
- As an FYI I have prototyped (but not implemented) the ability to use Hex commands instead of just Decimal commands. I've attached a PDF showing the current command set plus the command space made available if I switch to Hex commands. BUT - even if Hex is implemented I must maintain the equivalent Decimal commands for compatibility.

You mention the /80 command has been out for 3 months. I don't think that matters. You also mention that perhaps the /80 command really should have been /50, and now I agree. So here is another idea:
- How about making /50 do the same thing as /80, and /51 be the one that also returns the Short Form page?
- We can keep /80 just in case anyone used it ... but I'd bet my lunch that this is not the case. But since it doesn't hurt to have two commands do the same thing I think we can just keep /80 even if we create a duplicate /50.

By the way, the Short Form page returns the state of 16 pins if there is no PCF8574. It returns the state of 24 pins if the PCF8574 is present. I'm not sure if this is going to cause problems for anyone. I will just document this in the Manual. I considered making a new Short Form command to display 24 pins, but that is more code. I think it is okay that anyone adding the PCF8574 should understand that this increases the number of pins reported in the Short Form.

If I were to start over from scratch and I could ignore emulation of the original factory commands I would do all this differently. But that's not on my horizon.

Mike

**Comment by nielsonm236** [comment]
The PDF I sent shows /80 and /84, but I would eliminate /84 depending on the outcome of our discussion here.

**Comment by peoyli** [comment]
>     * I was thinking "What if we add more pins?". I thought we should keep the space above command /47 free in case that happened. But the reality is that /55 and /56 must be kept to maintain emulation of the original factory set. I can't add more than 3 more pins beyond the PCF8574 without bumping into /55 and /56 ... so this should not be a reason to avoid use of /50 as you have proposed.

It's a good idea to keep it compatible with implementations using the original firmware, so as you mention, you will soon run out of extra pin space (and probably also ROM and RAM space that could be of more use for other functions), even if not using /50 and up for controlling the pins. Without complicating thing, those who need more than 24 IOs could as easy add another controller and write the application to handle every next set of 24 IOs on other controllers (I did like that with the 'k74' parallel port controllers I'm replacing, I had two of them, controlling 8 ports each).

> You mention the /80 command has been out for 3 months. I don't think that matters. You also mention that perhaps the /80 command really should have been /50, and now I agree. So here is another idea:
> 
>     * How about making /50 do the same thing as /80, and /51 be the one that also returns the Short Form page?
> 
I just thought of that when I had /50 in use for the /80 with the returned result, so for me (and I'm the only one using it) /50 as an alias to /80 and /51 as /80 with result is fine.

>     * We can keep /80 just in case anyone used it ... but I'd bet my lunch that this is not the case. But since it doesn't hurt to have two commands do the same thing I think we can just keep /80 even if we create a duplicate /50.
> 
You can document /80 as 'deprecated' and replaced by /50, so that range could be made free for other use in a later version. As I see it, /8x should be used for 'one time settings' like the IO pinout option.

> By the way, the Short Form page returns the state of 16 pins if there is no PCF8574. It returns the state of 24 pins if the PCF8574 is present. I'm not sure if this is going to cause problems for anyone. I will just document this in the Manual. I considered making a new Short Form command to display 24 pins, but that is more code. I think it is okay that anyone adding the PCF8574 should understand that this increases the number of pins reported in the Short Form.
> 
I think keeping the 16-pin short form status command would be cleaner and more logical than having 24-pin output when no PCF8574 is present. Having 24-pin status returned for only 16 outputs will be confusing.

**Comment by nielsonm236** [comment]
On the last item (Short Form output) I probably was not clear.
a) If no PCF8574 the Short Form reports 16 pins just as it does now.
b) If there IS a PCF8574 the Short Form reports 24 pins.
Does that work?
If that does not work I can make /98 /99 report only 16 pins, and create a new command (maybe /97) that reports 24 pins but only if a PCF8574 is present. It is a little more code but can be done.

**Comment by peoyli** [comment]
You can keep the short form status command as is (16 pins without PCF8574 and 24 pins with)

**Comment by nielsonm236** [comment]
Okay! I think I know what to do now:
- Deprecate command /80
- New command /50 does what /80 used to do
- New command /51 does the same as /50, but returns the Short Form page
- The /50 and /51 commands only operate on pins 1 to 16
- The Short Form page is 16 pins if no PCF8574, and 24 pins if there IS a PCF8574

**Comment by nielsonm236** [comment]
Addressed in 20230305 1816

**Pull request closed without merging**
